//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValuPat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ValueDatabaseEntities : DbContext
    {
        public ValueDatabaseEntities()
            : base("name=ValueDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C00_P01_DPO> C00_P01_DPO { get; set; }
        public virtual DbSet<C00_P02_Titolare> C00_P02_Titolare { get; set; }
        public virtual DbSet<C00_P04_Responsabile> C00_P04_Responsabile { get; set; }
    }
}
